# Лабораторная работа №1

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [55]:
def zadanie1():
    print('Hello World!')

### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [ ]:
import random
import time
def generate_matrix(rows, cols, min_val, max_val):
    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)    
    return matrix

my_matrix = generate_matrix(3, 3, 0, 100)
print(my_matrix)

[[44, 86, 92], [66, 21, 44], [46, 19, 13]]


In [45]:
import random
user_m = int(input("m = "))
user_n = int(input("n = "))
user_min_limit = int(input())
user_max_limit = int(input())

matrix = []
for i in range(user_m):
    row = [random.randint(user_min_limit, user_max_limit) for _ in range(user_n)]
    matrix.append(row)

print("Матрица:")
for row in matrix:
    print(row)

Матрица:
[0, 6, 6]
[2, 7, 7]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [ ]:
# Сортировка выбором.
import copy
import random
import time

start_time = time.time()

def generate_matrix(rows, cols, min_val=0, max_val=100):

    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)
    return matrix

def selection_sort_matrix(matrix):

  rows = len(matrix)
  cols = len(matrix[0])
  N = rows * cols


  flat_list = [matrix[i][j] for i in range(rows) for j in range(cols)]


  for i in range(N - 1):
    min_val = flat_list[i]
    min_index = i
    for j in range(i + 1, N):
      if flat_list[j] < min_val:
        min_val = flat_list[j]
        min_index = j

    if min_index != i:
      flat_list[i], flat_list[min_index] = flat_list[min_index], flat_list[i]


  sorted_matrix = []
  for i in range(0, N, cols):
    sorted_matrix.append(flat_list[i:i + cols])

  return sorted_matrix


rows = 4
cols = 4
min_value = 2
max_value = 19

my_matrix = generate_matrix(rows, cols, min_value, max_value)

print("Исходная матрица:")
for row in my_matrix:
    print(row)

sorted_matrix = selection_sort_matrix(my_matrix)

print("\nОтсортированная матрица (построчно):")
for row in sorted_matrix:
    print(row)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

Исходная матрица:
[4, 2, 6, 17]
[16, 18, 16, 4]
[8, 13, 4, 9]
[9, 9, 5, 9]

Отсортированная матрица (построчно):
[2, 4, 4, 4]
[5, 6, 8, 9]
[9, 9, 9, 13]
[16, 16, 17, 18]
--- 1 ms ---


In [47]:
# Сортировка вставкой.
start_time = time.time()

import copy
import random

def generate_matrix(rows, cols, min_val=0, max_val=100):

    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)
    return matrix


def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key


def sort_matrix(matrix, cols):
    cop1 = copy.deepcopy(matrix)
    cop3 = []
    for row in cop1:
        cop3.extend(row)

    insertion_sort(cop3)

    sorte = []
    for i in range(0, len(cop3), cols):
        sorte.append(cop3[i:i + cols])
    return sorte


def print_matrix(matrix, title=""):
    if title:
        print(title)
    for row in matrix:
        print(row)


rows = 3 
cols = 4 
min_val = 0  
max_val = 100

    
mtx = generate_matrix(rows, cols, min_val, max_val)
print_matrix(mtx, "Исходная матрица:")

    
sorted_matrix = sort_matrix(mtx, user_n)

    
print_matrix(sorted_matrix, "Сортировка вставкой (по строкам):")

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

Исходная матрица:
[92, 44, 33, 19]
[98, 18, 84, 65]
[36, 89, 91, 72]
Сортировка вставкой (по строкам):
[18, 19, 33]
[36, 44, 65]
[72, 84, 89]
[91, 92, 98]
--- 2 ms ---


In [48]:
# Сортировка обменом. || Сортировка пузырьком.
start_time = time.time()

import random
import copy


def generate_matrix(rows, cols, min_val=0, max_val=100):
    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)
    return matrix


def bub_sor(A):
    for j in range(len(A) - 1):
        for i in range(len(A) - 1 - j):
            if A[i] > A[i + 1]:
                A[i], A[i + 1] = A[i + 1], A[i]


rows = int(input("Введите количество строк матрицы: "))
cols = int(input("Введите количество столбцов матрицы: "))
user_n = int(input("Введите размер подматрицы для вывода (N): "))


mtx = generate_matrix(rows, cols)
print("Исходная матрица:")
for row in mtx:
    print(row)


cop4 = copy.deepcopy(mtx)  
cop5 = []
for i in cop4:
    for i2 in i:
        cop5.append(i2)
N = len(cop5)
bub_sor(cop5)


sorte = []
for i in range(0, N, user_n):
    sorte.append(cop5[i:i + user_n])


print("\nСортировка пузырьком:")
for row in sorte:
    print(row)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

Исходная матрица:
[25, 77, 11]
[18, 44, 53]

Сортировка пузырьком:
[11, 18, 25, 44]
[53, 77]
--- 10782 ms ---


In [49]:
# Сортировка Шелла.
start_time = time.time()
import random

def generate_matrix(rows, cols, min_val=0, max_val=100):
    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)
    return matrix


def shell_sort(arr):

    n = len(arr)
    gap = n // 2

    while gap > 0:
        for i in range(gap, n):
            temp = arr[i]
            j = i
            while j >= gap and arr[j - gap] > temp:
                arr[j] = arr[j - gap]
                j -= gap
            arr[j] = temp
        gap //= 2
    return arr


def print_matrix(matrix):
    for row in matrix:
        print(row)

rows = 3
cols = 3
min_value = 0
max_value = 100

    
random_matrix = generate_matrix(rows, cols, min_value, max_value)

print("Исходная матрица:")
print_matrix(random_matrix)


    
sorted_matrix = []
for row in random_matrix:
    sorted_row = shell_sort(row)
    sorted_matrix.append(sorted_row)

print("\nМатрица с отсортированными строками (сортировка Шелла):")
print_matrix(sorted_matrix)


print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

Исходная матрица:
[24, 12, 85]
[66, 57, 68]
[10, 54, 41]

Матрица с отсортированными строками (сортировка Шелла):
[12, 24, 85]
[57, 66, 68]
[10, 41, 54]
--- 3 ms ---


In [50]:
# Быстрая сортировка.
start_time = time.time()
import random

def generate_matrix(rows, cols, min_val=0, max_val=100):
    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)
    return matrix

def print_matrix(matrix):
    for row in matrix:
        print(row)

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]  
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

rows = 5
cols = 4
min_value = 0
max_value = 100

random_matrix = generate_matrix(rows, cols, min_value, max_value)
print("Исходная матрица:")
print_matrix(random_matrix)

flat_list = [element for row in random_matrix for element in row]

sorted_list = quicksort(flat_list)

sorted_matrix = []
for i in range(rows):
    sorted_matrix.append(sorted_list[i*cols:(i+1)*cols])

print("\nОтсортированная матрица:")
print_matrix(sorted_matrix)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
    

Исходная матрица:
[18, 67, 86, 18]
[37, 77, 85, 53]
[80, 42, 28, 38]
[84, 66, 79, 3]
[82, 52, 12, 57]

Отсортированная матрица:
[3, 12, 18, 18]
[28, 37, 38, 42]
[52, 53, 57, 66]
[67, 77, 79, 80]
[82, 84, 85, 86]
--- 2 ms ---


In [51]:
# Турнирная сортировка
import heapq
import time
import random

start_time = time.time()


def tournament_sort(data):
    size = len(data)
    if size <= 1:
        return data 

    heap = []
    for i in range(0, size, 2):
        if i + 1 < size:
            heap.append(min(data[i], data[i + 1]))
        else:
            heap.append(data[i]) 

    heapq.heapify(heap)

    sorted_list = []
    indices = {}

    for element in heap:
        indices[element] = [i for i, x in enumerate(data) if x == element][
            0] 

    while heap:
        winner = heapq.heappop(heap)
        sorted_list.append(winner)

        winner_index = indices[winner]
        pair_index = winner_index ^ 1 

        if pair_index < size:
            try:
                index_in_heap = heap.index(winner)  
            except ValueError:
                index_in_heap = -1

            if index_in_heap >= 0:
                loser = data[pair_index]

                heapq.heappush(heap, loser)
                indices[loser] = pair_index

    return sorted_list


def generate_matrix(rows, cols, min_val, max_val):
    matrix = []
    for _ in range(rows):
        row = [random.randint(min_val, max_val) for _ in range(cols)]
        matrix.append(row)
    return matrix

rows = 5
cols = 5
min_val = 1
max_val = 100

random_matrix = generate_matrix(rows, cols, min_val, max_val)

print("Original Matrix:")
for row in random_matrix:
    print(row)

flattened_list = [element for row in random_matrix for element in row]

sorted_data = tournament_sort(flattened_list)

print("\nSorted Flattened List:")
print(sorted_data)

print("--- {0} ms ---".format(round((time.time() - start_time) * 1000)))

Original Matrix:
[79, 13, 11, 57, 15]
[6, 25, 12, 95, 44]
[50, 99, 70, 44, 27]
[30, 42, 68, 84, 84]
[50, 57, 20, 48, 73]

Sorted Flattened List:
[6, 11, 12, 13, 20, 27, 42, 44, 44, 50, 50, 73, 84, 95, 99]
--- 2 ms ---


In [52]:
# Пирамидальная сортировка
import time
import random
import numpy as np

start_time = time.time()

def heapify(arr, n, i):
  largest = i  
  left = 2 * i + 1 
  right = 2 * i + 2 

  if left < n and arr[i] < arr[left]:
    largest = left

  if right < n and arr[largest] < arr[right]:
    largest = right

  if largest != i:
    arr[i], arr[largest] = arr[largest], arr[i]

    heapify(arr, n, largest)


def heap_sort(arr, matrix_size=None):
  n = len(arr)
  if matrix_size is not None:
      matrix_rows, matrix_cols = matrix_size
      print("Исходная матрица:")
      print(np.array(arr).reshape((matrix_rows, matrix_cols)))
      print("-" * 20)


  for i in range(n // 2 - 1, -1, -1): 
    heapify(arr, n, i)
    if matrix_size is not None:
        print(f"После heapify {i} - формирование Max-кучи:")
        print(np.array(arr).reshape((matrix_rows, matrix_cols)))
        print("-" * 20)

  for i in range(n - 1, 0, -1):
    arr[0], arr[i] = arr[i], arr[0]
    if matrix_size is not None:
        print(f"Меняем arr[0] и arr[{i}]")
        print(np.array(arr).reshape((matrix_rows, matrix_cols)))
        print("-" * 20)

    heapify(arr, i, 0)
    if matrix_size is not None:
        try:
            print(f"После heapify (размер кучи {i}):")
            print(np.array(arr[:i]).reshape((matrix_rows, matrix_cols)))
            print("-" * 20)

        except ValueError:
            print(f"  Невозможно отобразить кучу размера {i} в матрицу {matrix_rows}x{matrix_cols}")
            print(f"  Текущий размер массива arr[:{i}]: {len(arr[:i])}")
            print("-" * 20)
  return arr

start_time = time.time()
matrix_rows = 3
matrix_cols = 4
matrix_size = (matrix_rows, matrix_cols)
arr = [random.randint(1, 99) for _ in range(matrix_rows * matrix_cols)]

print("Размер матрицы:", matrix_size)
sorted_arr = heap_sort(arr, matrix_size)
print("Отсортированная матрица (как одномерный массив):", sorted_arr)

print("--- {0} ms ---".format(round((time.time() - start_time) * 1000)))

Размер матрицы: (3, 4)
Исходная матрица:
[[39 50 38 63]
 [84 26 11 43]
 [44 43 26 15]]
--------------------
После heapify 5 - формирование Max-кучи:
[[39 50 38 63]
 [84 26 11 43]
 [44 43 26 15]]
--------------------
После heapify 4 - формирование Max-кучи:
[[39 50 38 63]
 [84 26 11 43]
 [44 43 26 15]]
--------------------
После heapify 3 - формирование Max-кучи:
[[39 50 38 63]
 [84 26 11 43]
 [44 43 26 15]]
--------------------
После heapify 2 - формирование Max-кучи:
[[39 50 38 63]
 [84 26 11 43]
 [44 43 26 15]]
--------------------
После heapify 1 - формирование Max-кучи:
[[39 84 38 63]
 [50 26 11 43]
 [44 43 26 15]]
--------------------
После heapify 0 - формирование Max-кучи:
[[84 63 38 44]
 [50 26 11 43]
 [39 43 26 15]]
--------------------
Меняем arr[0] и arr[11]
[[15 63 38 44]
 [50 26 11 43]
 [39 43 26 84]]
--------------------
После heapify (размер кучи 11):
  Невозможно отобразить кучу размера 11 в матрицу 3x4
  Текущий размер массива arr[:11]: 11
--------------------
Меняем a

### Вывод
